---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - VERSION=docker
      - PLEX_CLAIM=claim-NwiN9-7v6Z1agVyvCjyz
    volumes:
      - /home/pi/docker/plex/config:/config
      - /mnt/unidadusb/Series:/tv
      - /mnt/unidadusb/Peliculas:/movies
    restart: unless-stopped

