---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - JELLYFIN_PublishedServerUrl=192.168.3.2
    volumes:
      - /mnt/unidadusb/library/Library:/config
      - /mnt/unidadusb/Series:/data/tvshows
      - /mnt/unidadusb/Peliculas:/data/movies
    ports:
      - 8096:8096
     # - 8920:8920 #optional
     # - 7359:7359/udp #optional
     # - 1900:1900/udp #optional
    restart: unless-stopped
