#version: '3.3'
services:
    docker-controller-bot:
        environment:
            - TELEGRAM_TOKEN=7281066440:AAE9i-fUU9Gkj-HyETfkB_UK-QRMnKKnojM
            - TELEGRAM_ADMIN=1818312382
            - CONTAINER_NAME=docker-controller-bot
            - TZ=America/Santiago
            #- TELEGRAM_GROUP=
            #- TELEGRAM_THREAD=1
            #- TELEGRAM_NOTIFICATION_CHANNEL=
            - CHECK_UPDATES=1
            - CHECK_UPDATE_EVERY_HOURS=168
            - BUTTON_COLUMNS=2
            - LANGUAGE=ES
            - EXTENDED_MESSAGES=0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
        image: dgongut/docker-controller-bot:latest
        container_name: docker-controller-bot
        restart: always
        network_mode: host
        tty: true
