---
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - SUBDOMAINS=daver2024
      - TOKEN=3c9b31c5-3a83-407e-befb-67ce78b43482
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - /home/pi/docker/duckdns/config:/config
    restart: unless-stopped
