#version: '3.8'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/pi/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9009:9001"
    volumes:
      - /home/pi/docker/mosquitto/config:/mosquitto/config
      - /home/pi/docker/mosquitto/data:/mosquitto/data
      - /home/pi/docker/mosquitto/log:/mosquitto/log
    environment:
      - TZ=America/Santiago

  tuyamqtt:
    image: thehookup/tuya-mqtt
    container_name: tuyamqtt
    restart: unless-stopped
    ports:
      - "8883:8883"
    env_file:
      - .env
    volumes:
      - /home/pi/docker/tuya-mqtt/cache:/cache


#Solo para el archivo .env
# Tuya MQTT credentials
TUYA_USERNAME=tu_correo_tuya
TUYA_PASSWORD=tu_contraseña_tuya
TUYA_ACCESS_ID=tu_access_id
TUYA_ACCESS_SECRET=tu_access_secret

# MQTT broker settings
MQTT_HOST=localhost
MQTT_PORT=1883

