#version: '3'
services:
  netdata:
    image: netdata/netdata:edge
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NETDATA_CLAIM_TOKEN=824AWbUP3Qag6yx3ru4F7ZLVbepxlQxKNMgd3B2zeU9YzJxz3H7z4LpI4E-0XqKcbqxRC1flgy6gseY1oYswSgjMTQr2TquPzbtU9rN8z1BTwO9ZOx0DhOjPw2VbXStK1yAu00o
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=de9f46d3-cf37-4c70-99c0-b0a382a75284
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
