#version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
      - VERSION=docker
      - PLEX_CLAIM=claim-pqhopRuGz_emx1VUcVd8
    volumes:
      - /home/pi/docker/plex/config:/config
      - /mnt/nas/Series:/tv
      - /mnt/nas/Peliculas:/movies
    restart: unless-stopped
