services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=${WG_HOST}

      # ⚠️ Change the Web UI Password:
      - PASSWORD_HASH=${PASSWORD_HASH}

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /home/pi/docker/wg-pihole:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      # ⚠️ Change the Web UI Password:
      - WEBPASSWORD=${WEBPASSWORD}
      - TZ=${TZ}
    volumes:
      - /home/pi/docker/wg-pihole/config:/etc/pihole
      - /home/pi/docker/wg-pihole/dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
