#version: '3.3'
services:
  minecraft-bedrock-server:
    image: itzg/minecraft-bedrock-server
    container_name: mc
    environment:
      - EULA=TRUE
      - SERVER_PORT=19132
      - DIFFICULTY=easy
      # - LEVEL_SEED= semilla opcional para generar tu mundo
    ports:
      - "19132:19132/udp"
    volumes:
      - mc:/data

volumes:
  mc:
